name: Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 */1 * *" # At 00:00 on every day-of-month.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    name: Prebuild stuff
    steps:
      - uses: actions/checkout@v2
      - name: Do stuff with Node ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
      - with:
        node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run postbuild
