name: Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 */1 * *" # At 00:00 on every day-of-month.

jobs:
  first-job:
    runs-on: ubuntu-latest
    name: Prebuild stuff
    steps:
      - name: Postbuild
        run: npm run postbuild
